apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: redispassword
spec:
  vault:
    name: dp-dev-cu-kv-1-replica # name of key vault
    object:
      name: REDISPASSWORD # name of the akv object
      type: secret # akv object type

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: jwtpublickey
spec:
  vault:
    name: dp-dev-cu-kv-1-replica # name of key vault
    object:
      name: JWTPUBLICKEY # name of the akv object
      type: secret # akv object type

---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: appinsightskey
spec:
  vault:
    name: dp-dev-cu-kv-1-replica # name of key vault
    object:
      name: APPINSIGHTSKEY # name of the akv object
      type: secret # akv object type