{{- $chartName := "gx-api-payment"}}

{{- $brands := .Values.brands }}
{{- range $brands }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .name }}{{ .environment }}-{{ .version }}-{{ $chartName }}
  labels:
    app: {{ .name }}{{ .environment }}-{{ .version }}-{{ $chartName }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .name }}{{ .environment }}-{{ .version }}-{{ $chartName }}
  minReplicas: {{ .autoscaling.minReplicas }}
  maxReplicas: {{ .autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .autoscaling.targetMemoryUtilizationPercentage }}
---          
{{- end }}