name: Publish to npm

on:
  release:
    types: [created]
      

permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@focus-brands'

      - name: create npmrc file
        shell: bash
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${PAT}" > .npmrc
          echo "@focus-brands:registry=https://npm.pkg.github.com" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Install Dependencies
        run: npm install
      
      - name: Get the tag
        id: get_tag
        run: echo ::set-output name=TAG::${GITHUB_REF/refs\/tags\//}

      - name: Print the tag
        run: echo ${{ steps.get_tag.outputs.TAG }}

      - name: Set Git User Email
        run: git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Set Git User Name
        run: git config --global user.name "github-actions[bot]"

      - name: Update Version
        run: npm version ${{ steps.get_tag.outputs.TAG }}

      - name: Publish Package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
