name: Test Case Run Check

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - phtndev
      - phtnqa
      - fbqa
      - fbuat
      - main

jobs:
  Test-Case-Check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@focus-brands'

      - name: Replace the token in npmrc file
        shell: bash
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sed -i.back "s|NODE_AUTH_TOKEN|${PAT}|g" .npmrc

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test:cov

      - name: Run eslint
        run: npm run lint:test
