name: Veracode Pipeline Check

on:
  pull_request:
    # Sequence of patterns matched against refs/heads
    branches:
      - develop
      - main

jobs:
  veracode-run:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: actions/setup-java@v1 # Make java accessible on path so the uploadandscan action can run.
        with:
          java-version: "8"

      - uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://npm.pkg.github.com"
          scope: "@focus-brands"

      - name: Create the token in npmrc file
        shell: bash
        env:
          PAT: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "//npm.pkg.github.com/:_authToken=${PAT}" > .npmrc
          echo "@focus-brands:registry=https://npm.pkg.github.com" >> .npmrc
          echo "always-auth=true" >> .npmrc

      - name: Extract Repository Name
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2 | tr -d '-')
          echo "Repository Name: $REPO_NAME"
          echo "REPO_NAME=$REPO_NAME" >> $GITHUB_ENV

      - name: npm install, build, and test
        run: |
          npm install

      - name: Zip artifact for deployment
        run: zip -r ${{ env.REPO_NAME }}.zip src package.json package-lock.json

      - name: Veracode Pipeline Scan
        uses: veracode/Veracode-pipeline-scan-action@v1.0.10
        with:
          project_name: "NGDP~GH~${{ github.event.repository.name }}"
          createprofile: false
          file: "${{ env.REPO_NAME }}.zip"
          vid: ${{ secrets.VERACODE_ADAM_ID }}
          vkey: ${{ secrets.VERACODE_ADAM_SECRET }}
